# Generated by Django 5.2.6 on 2025-09-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "preco_unidade",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                ("unidade_medida", models.CharField(default="g", max_length=20)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="pizzas/")),
                ("preco_base", models.DecimalField(decimal_places=2, max_digits=8)),
                ("modo_preparo", models.IntegerField()),
                ("tempo_preparo", models.IntegerField()),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("icone", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True)),
                ("cor_hex", models.CharField(default="#FF6B6", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientePizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_numerica",
                    models.DecimalField(decimal_places=3, max_digits=8),
                ),
                ("quantidade_texto", models.CharField(blank=True, max_length=50)),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.ingrediente",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cardapio.pizza"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="tipo_ingrediente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cardapio.tipoingrediente",
            ),
        ),
        migrations.AddField(
            model_name="pizza",
            name="tipo_pizza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cardapio.tipopizza"
            ),
        ),
    ]
